/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Tabscreens/maindashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Tabscreens/plangenerate`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Tabscreens/selectedexercise`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Tabscreens/userscreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/navigatescreens/customerexercise`; params?: Router.UnknownInputParams; } | { pathname: `/screens/navigatescreens/details`; params?: Router.UnknownInputParams; } | { pathname: `/screens/navigatescreens/editexercises`; params?: Router.UnknownInputParams; } | { pathname: `/signupscreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Tabscreens/maindashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Tabscreens/plangenerate`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Tabscreens/selectedexercise`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Tabscreens/userscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/navigatescreens/customerexercise`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/navigatescreens/details`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/navigatescreens/editexercises`; params?: Router.UnknownOutputParams; } | { pathname: `/signupscreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/Tabscreens/maindashboard${`?${string}` | `#${string}` | ''}` | `/screens/Tabscreens/plangenerate${`?${string}` | `#${string}` | ''}` | `/screens/Tabscreens/selectedexercise${`?${string}` | `#${string}` | ''}` | `/screens/Tabscreens/userscreen${`?${string}` | `#${string}` | ''}` | `/screens/navigatescreens/customerexercise${`?${string}` | `#${string}` | ''}` | `/screens/navigatescreens/details${`?${string}` | `#${string}` | ''}` | `/screens/navigatescreens/editexercises${`?${string}` | `#${string}` | ''}` | `/signupscreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Tabscreens/maindashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Tabscreens/plangenerate`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Tabscreens/selectedexercise`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Tabscreens/userscreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/navigatescreens/customerexercise`; params?: Router.UnknownInputParams; } | { pathname: `/screens/navigatescreens/details`; params?: Router.UnknownInputParams; } | { pathname: `/screens/navigatescreens/editexercises`; params?: Router.UnknownInputParams; } | { pathname: `/signupscreen`; params?: Router.UnknownInputParams; };
    }
  }
}
