/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/customerexercise`; params?: Router.UnknownInputParams; } | { pathname: `/screens/customerexercise/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/maindashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/maindashboard/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/selectedexercise`; params?: Router.UnknownInputParams; } | { pathname: `/screens/selectedexercise/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/userscreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/userscreen/styles`; params?: Router.UnknownInputParams; } | { pathname: `/signupscreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/customerexercise`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/customerexercise/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/maindashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/maindashboard/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/selectedexercise`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/selectedexercise/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/userscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/userscreen/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/signupscreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/customerexercise${`?${string}` | `#${string}` | ''}` | `/screens/customerexercise/styles${`?${string}` | `#${string}` | ''}` | `/screens/maindashboard${`?${string}` | `#${string}` | ''}` | `/screens/maindashboard/styles${`?${string}` | `#${string}` | ''}` | `/screens/selectedexercise${`?${string}` | `#${string}` | ''}` | `/screens/selectedexercise/styles${`?${string}` | `#${string}` | ''}` | `/screens/userscreen${`?${string}` | `#${string}` | ''}` | `/screens/userscreen/styles${`?${string}` | `#${string}` | ''}` | `/signupscreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/customerexercise`; params?: Router.UnknownInputParams; } | { pathname: `/screens/customerexercise/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/maindashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/maindashboard/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/selectedexercise`; params?: Router.UnknownInputParams; } | { pathname: `/screens/selectedexercise/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/userscreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/userscreen/styles`; params?: Router.UnknownInputParams; } | { pathname: `/signupscreen`; params?: Router.UnknownInputParams; };
    }
  }
}
